version: '3.3'
services:
  user_management_api:
    container_name: user-management-app_container
    image: user-management-app_container
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=Joy2Dworld
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_db
